added if

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -165,10 +165,30 @@ workflows:
 
           - name: Build AAB with Flutter
             script: |
-              BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
+              LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
+              if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+              else
+                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+              fi
               flutter build appbundle --release \
-                --build-name=1.0.$BUILD_NUMBER \
-                --build-number=$BUILD_NUMBER
+                --build-name=1.0.$UPDATED_BUILD_NUMBER \
+                --build-number=$UPDATED_BUILD_NUMBER
+
+              # LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+              # if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+              #   # fallback in case no build number was found from Google Play.
+              #   # Alternatively, you can `exit 1` to fail the build
+              #   # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+              #   # of times this workflow has been built
+              #   UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+              # else
+              #   UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+              # fi
+              # cd android
+              # ./gradlew bundleRelease \
+              #   -PversionCode=$UPDATED_BUILD_NUMBER \
+              #   -PversionName=1.0.$UPDATED_BUILD_NUMBER
         artifacts:
           - build/**/outputs/**/*.aab
           - build/**/outputs/**/mapping.txt
