- name: 🚀 Shorebird release             script:  shorebird release android

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -79,10 +79,11 @@ workflows:
               curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
 
               # Add Shorebird to PATH
-              #echo PATH="/home/builder/.shorebird/bin:$PATH" >> $CM_ENV
               echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
           - name: 🚀 Shorebird INIT
             script:  shorebird init
+          - name: 🚀 Shorebird release
+            script:  shorebird release android
           - name: 🚀 Shorebird Patch
             script:  shorebird patch android --force
           - name: Set up local.properties
@@ -202,187 +203,245 @@ workflows:
                   $CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols -gsp ios/Runner/GoogleService-Info.plist -p ios $dsymPath
                 fi
 
+    shorebird-workflow: 
+        name: shorebird Workflow
+        max_build_duration: 120
+        instance_type: mac_mini_m1
+        labels:
+          - ${PACKAGE_NAME}
+        environment:
+          #flutter: fvm
+          android_signing:
+            - testKeystore
+          groups:
+            - shorebird_token
+            - firebase_credentials
+            - google_credentials3
+          vars:
+            PACKAGE_NAME: "io.codemagic.dtrdic6"
+            GOOGLE_PLAY_TRACK: internal
+        triggering:
+          events:
+              - push
+          branch_patterns:
+          - pattern: "main"
+        scripts:
+          - name: Build aab
+            script: | 
+                flutter build appbundle 
+          - name: 🐦 Setup Shorebird
+            script: |
+              # Install Shorebird
+              curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
 
-  # ios-workflow:
-  #   name: iOS Firebase Crashlytics
-  #   max_build_duration: 120
-  #   integrations:
-  #     app_store_connect: codemagic
-  #   environment:
-  #     ios_signing:
-  #       distribution_type: app_store
-  #       bundle_identifier: io.codemagic.firebaseCrash
-  #     vars:
-  #       XCODE_WORKSPACE: "ios/Runner.xcworkspace"
-  #       XCODE_SCHEME: "Runner"
-  #       APP_ID: 1555555551
-  #     flutter: stable
-  #     xcode: 13.2
-  #     cocoapods: default
-  #   scripts:
-  #     - name: Get Flutter Packages
-  #       script: |
-  #         flutter packages pub get
-  #     - name: Pod install
-  #       script: |
-  #         find . -name "Podfile" -execdir pod install \;
-  #     - name: Set up code signing settings on Xcode project
-  #       script: |
-  #         xcode-project use-profiles
-  #     - name: Flutter build ipa and automatic versioning
-  #       script: |
-  #         flutter build ipa --release \
-  #         --build-name=1.0.0 \
-  #         --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1)) \
-  #         --export-options-plist=/Users/builder/export_options.plist
-  #   artifacts:
-  #     - build/ios/ipa/*.ipa
-  #     - /tmp/xcodebuild_logs/*.log
-  #     - flutter_drive.log
-  #     - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
-  #   publishing:
-  #     scripts:
-  #       - name: Crashlytics
-  #         script: |
-  #           echo "Find build artifacts"
-  #           dsymPath=$(find $CM_BUILD_DIR/build/ios/archive/Runner.xcarchive -name "*.dSYM" | head -1)
-  #           if [[ -z ${dsymPath} ]]
-  #           then
-  #             echo "No debug symbols were found, skip publishing to Firebase Crashlytics"
-  #           else
-  #             echo "Publishing debug symbols from $dsymPath to Firebase Crashlytics"
-  #             ls -d -- ios/Pods/*
-  #             $CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols \
-  #               -gsp ios/Runner/GoogleService-Info.plist \
-  #               -p ios $dsymPath
-  #           fi
+              # Add Shorebird to PATH
+              echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
+          - name: 🚀 Shorebird INIT
+            script:  shorebird init
+          - name: 🚀 Shorebird release
+            script:  shorebird release android
+          - name: 🚀 Shorebird Patch
+            script:  shorebird patch android --force
+        
+        artifacts:
+          - build/**/outputs/**/*.aab
+          - build/**/outputs/**/mapping.txt
+          - flutter_drive.log
+          - debug-info.zip
+        publishing:
+          # firebase:
+          #     firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
+          #     android:
+          #       app_id: 1:701760780130:android:78886c544e828688f09e3b
+          email:
+            recipients:
+              - david@nevercode.io
+          google_play:
+            credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS3
+            track: internal
+            changes_not_sent_for_review: true
+            submit_as_draft: true
 
-  # android-workflow2:
-        # name: Android Workflow
-        # max_build_duration: 120
-        # instance_type: linux_x2
-        # labels:
-        # - ${PACKAGE_NAME}
-        # environment:
-        #   flutter: fvm
-        #   android_signing:
-        #     - testKeystore
-        #   groups:
-        #     - firebase_credentials
-        #     - google_play_credentials2
-        #   java: 11
-        #   vars:
-        #     PACKAGE_NAME: "io.codemagic.dtrdic6"
-        # # triggering:
-        # #   events:
-        # #       #- pull_request 
-        # #       - push
-        #   # branch_patterns:
-        #   # - pattern: "main"
-        #   #   include: true
-        #   #   source: false
-        # scripts:
-        #   - name: Decode Google credentials 
-        #     script: |
-        #       echo $FIREBASE_SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
+        # ios-workflow:
+        #   name: iOS Firebase Crashlytics
+        #   max_build_duration: 120
+        #   integrations:
+        #     app_store_connect: codemagic
+        #   environment:
+        #     ios_signing:
+        #       distribution_type: app_store
+        #       bundle_identifier: io.codemagic.firebaseCrash
+        #     vars:
+        #       XCODE_WORKSPACE: "ios/Runner.xcworkspace"
+        #       XCODE_SCHEME: "Runner"
+        #       APP_ID: 1555555551
+        #     flutter: stable
+        #     xcode: 13.2
+        #     cocoapods: default
+        #   scripts:
+        #     - name: Get Flutter Packages
+        #       script: |
+        #         flutter packages pub get
+        #     - name: Pod install
+        #       script: |
+        #         find . -name "Podfile" -execdir pod install \;
+        #     - name: Set up code signing settings on Xcode project
+        #       script: |
+        #         xcode-project use-profiles
+        #     - name: Flutter build ipa and automatic versioning
+        #       script: |
+        #         flutter build ipa --release \
+        #         --build-name=1.0.0 \
+        #         --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1)) \
+        #         --export-options-plist=/Users/builder/export_options.plist
+        #   artifacts:
+        #     - build/ios/ipa/*.ipa
+        #     - /tmp/xcodebuild_logs/*.log
+        #     - flutter_drive.log
+        #     - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
+        #   publishing:
+        #     scripts:
+        #       - name: Crashlytics
+        #         script: |
+        #           echo "Find build artifacts"
+        #           dsymPath=$(find $CM_BUILD_DIR/build/ios/archive/Runner.xcarchive -name "*.dSYM" | head -1)
+        #           if [[ -z ${dsymPath} ]]
+        #           then
+        #             echo "No debug symbols were found, skip publishing to Firebase Crashlytics"
+        #           else
+        #             echo "Publishing debug symbols from $dsymPath to Firebase Crashlytics"
+        #             ls -d -- ios/Pods/*
+        #             $CM_BUILD_DIR/ios/Pods/FirebaseCrashlytics/upload-symbols \
+        #               -gsp ios/Runner/GoogleService-Info.plist \
+        #               -p ios $dsymPath
+        #           fi
 
-        #   # - name: Edit JAVA OPTS
-        #   #   script: |
-        #   #     export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
-        #   #     # or
-        #   #     # If the above code does not take effect, then export the java.xml.bind like below code.
-        #   #     #export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.xml.bind'
-         
-        #   # - name: Install Android NDK
-        #   #   script: |
-        #   #       set -e
-        #   #       set -x
-        #   #       NDK_VERSION="android-ndk-r23c"
-        #   #       NDK_URL="https://dl.google.com/android/repository/${NDK_VERSION}-linux.zip"
-        #   #       NDK_DIR="android-ndk23"
+        # android-workflow2:
+              # name: Android Workflow
+              # max_build_duration: 120
+              # instance_type: linux_x2
+              # labels:
+              # - ${PACKAGE_NAME}
+              # environment:
+              #   flutter: fvm
+              #   android_signing:
+              #     - testKeystore
+              #   groups:
+              #     - firebase_credentials
+              #     - google_play_credentials2
+              #   java: 11
+              #   vars:
+              #     PACKAGE_NAME: "io.codemagic.dtrdic6"
+              # # triggering:
+              # #   events:
+              # #       #- pull_request 
+              # #       - push
+              #   # branch_patterns:
+              #   # - pattern: "main"
+              #   #   include: true
+              #   #   source: false
+              # scripts:
+              #   - name: Decode Google credentials 
+              #     script: |
+              #       echo $FIREBASE_SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS
 
-        #   #       # Create the target directory
-        #   #       mkdir -p ${NDK_DIR}
+              #   # - name: Edit JAVA OPTS
+              #   #   script: |
+              #   #     export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
+              #   #     # or
+              #   #     # If the above code does not take effect, then export the java.xml.bind like below code.
+              #   #     #export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.xml.bind'
+              
+              #   # - name: Install Android NDK
+              #   #   script: |
+              #   #       set -e
+              #   #       set -x
+              #   #       NDK_VERSION="android-ndk-r23c"
+              #   #       NDK_URL="https://dl.google.com/android/repository/${NDK_VERSION}-linux.zip"
+              #   #       NDK_DIR="android-ndk23"
 
-        #   #       # Download NDK
-        #   #       curl -o ${NDK_VERSION}.zip ${NDK_URL}
-        #   #       unzip -q ${NDK_VERSION}.zip -d ${NDK_DIR}
-        #   #       rm ${NDK_VERSION}.zip
+              #   #       # Create the target directory
+              #   #       mkdir -p ${NDK_DIR}
 
-        #   #       # Set NDK environment variable
-        #   #       export ANDROID_NDK_HOME=${NDK_DIR}/${NDK_VERSION}
+              #   #       # Download NDK
+              #   #       curl -o ${NDK_VERSION}.zip ${NDK_URL}
+              #   #       unzip -q ${NDK_VERSION}.zip -d ${NDK_DIR}
+              #   #       rm ${NDK_VERSION}.zip
 
-        #   #       # Add NDK to PATH
-        #   #       export PATH=${ANDROID_NDK_HOME}:$PATH
+              #   #       # Set NDK environment variable
+              #   #       export ANDROID_NDK_HOME=${NDK_DIR}/${NDK_VERSION}
 
-        #   #       # Print NDK version
-        #   #       ndk-build --version
+              #   #       # Add NDK to PATH
+              #   #       export PATH=${ANDROID_NDK_HOME}:$PATH
 
-        #   # - name: SUpdate build tools with Android SDK manager
-        #   #   script: |
-        #   #     set -e
-        #   #     set -x
-        #   #     $ANDROID_SDK_ROOT/tools/bin/sdkmanager --install "build-tools;33.0.0" && cd /usr/local/share/android-sdk/build-tools/33.0.0 \
-        #   #     && mv d8 dx \
-        #   #     && cd lib \
-        #   #     && mv d8.jar dx.jar
+              #   #       # Print NDK version
+              #   #       ndk-build --version
 
-        #   - name: Update build tools with Android SDK manager
-        #     script: |
-        #       # Set the Android home directory
-        #       ANDROID_HOME="$HOME/android-sdk"
+              #   # - name: SUpdate build tools with Android SDK manager
+              #   #   script: |
+              #   #     set -e
+              #   #     set -x
+              #   #     $ANDROID_SDK_ROOT/tools/bin/sdkmanager --install "build-tools;33.0.0" && cd /usr/local/share/android-sdk/build-tools/33.0.0 \
+              #   #     && mv d8 dx \
+              #   #     && cd lib \
+              #   #     && mv d8.jar dx.jar
 
-        #       # Set the download URL and file name
-        #       SDK_TOOLS_VERSION="6200805"
-        #       SDK_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-${SDK_TOOLS_VERSION}_latest.zip"
-        #       SDK_TOOLS_FILE="sdk-tools.zip"
+              #   - name: Update build tools with Android SDK manager
+              #     script: |
+              #       # Set the Android home directory
+              #       ANDROID_HOME="$HOME/android-sdk"
 
-        #       # Create the command-line tools directory
-        #       CMDLINE_TOOLS_DIR="${ANDROID_HOME}/command-line-tools"
-        #       mkdir -p "${CMDLINE_TOOLS_DIR}"
+              #       # Set the download URL and file name
+              #       SDK_TOOLS_VERSION="6200805"
+              #       SDK_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-${SDK_TOOLS_VERSION}_latest.zip"
+              #       SDK_TOOLS_FILE="sdk-tools.zip"
 
-        #       # Download the SDK Command-line Tools
-        #       curl -o "${SDK_TOOLS_FILE}" "${SDK_TOOLS_URL}"
+              #       # Create the command-line tools directory
+              #       CMDLINE_TOOLS_DIR="${ANDROID_HOME}/command-line-tools"
+              #       mkdir -p "${CMDLINE_TOOLS_DIR}"
 
-        #       # Unpack the SDK Command-line Tools to the appropriate directory
-        #       unzip -q "${SDK_TOOLS_FILE}" -d "${CMDLINE_TOOLS_DIR}"
+              #       # Download the SDK Command-line Tools
+              #       curl -o "${SDK_TOOLS_FILE}" "${SDK_TOOLS_URL}"
 
-        #       # Clean up the downloaded zip file
-        #       rm "${SDK_TOOLS_FILE}"
+              #       # Unpack the SDK Command-line Tools to the appropriate directory
+              #       unzip -q "${SDK_TOOLS_FILE}" -d "${CMDLINE_TOOLS_DIR}"
 
-        #       # Set the environment variables
-        #       export ANDROID_SDK_ROOT="${CMDLINE_TOOLS_DIR}"
-        #       export PATH="${ANDROID_SDK_ROOT}/bin:${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
+              #       # Clean up the downloaded zip file
+              #       rm "${SDK_TOOLS_FILE}"
 
-
-        #   - name: Set up local.properties
-        #     script: |
-        #       echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
-        #   - name: Get Flutter packages
-        #     script: |
-        #       flutter packages pub get
-
-
-        #   - name: Build AAB with Flutter
-        #     script: |
-        #       BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
-        #       flutter build appbundle --release \
-        #         --build-name=1.0.$BUILD_NUMBER \
-        #         --build-number=$BUILD_NUMBER
-        # artifacts:
-        #   - build/**/outputs/**/*.aab
-        #   - build/**/outputs/**/mapping.txt
-        #   - flutter_drive.log
-        # publishing:
-        #   firebase:
-        #       firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
-        #       android:
-        #         app_id: 1:1037460898728:android:d0779b82fdcb0f3e95539d
-        #   # google_play:
-        #   #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS2
-        #   #   track: internal
-        #   #   submit_as_draft: true
-
+              #       # Set the environment variables
+              #       export ANDROID_SDK_ROOT="${CMDLINE_TOOLS_DIR}"
+              #       export PATH="${ANDROID_SDK_ROOT}/bin:${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
 
 
-#test1
+              #   - name: Set up local.properties
+              #     script: |
+              #       echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
+              #   - name: Get Flutter packages
+              #     script: |
+              #       flutter packages pub get
+
+
+              #   - name: Build AAB with Flutter
+              #     script: |
+              #       BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
+              #       flutter build appbundle --release \
+              #         --build-name=1.0.$BUILD_NUMBER \
+              #         --build-number=$BUILD_NUMBER
+              # artifacts:
+              #   - build/**/outputs/**/*.aab
+              #   - build/**/outputs/**/mapping.txt
+              #   - flutter_drive.log
+              # publishing:
+              #   firebase:
+              #       firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
+              #       android:
+              #         app_id: 1:1037460898728:android:d0779b82fdcb0f3e95539d
+              #   # google_play:
+              #   #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS2
+              #   #   track: internal
+              #   #   submit_as_draft: true
+
+
+
+      #test1
